In [2]:
import numpy as onp
import jax.numpy as jnp
import jax

In [26]:
np_arr = onp.random.normal(size=(10,)).astype("float32")
jax_arr = jnp.asarray(np_arr)

In [27]:
np_arr

array([ 1.4163738 , -0.21575388,  0.11166906,  0.7651887 , -1.7619236 ,
       -0.50367457, -0.9007567 ,  0.34611902, -0.63155544, -0.42322147],
      dtype=float32)

In [28]:
jax_arr

DeviceArray([ 1.4163738 , -0.21575388,  0.11166906,  0.7651887 ,
             -1.7619236 , -0.50367457, -0.9007567 ,  0.34611902,
             -0.63155544, -0.42322147], dtype=float32)

In [29]:
onp.gradient(np_arr)

array([-1.6321278 , -0.6523524 ,  0.4904713 , -0.9367963 , -0.6344316 ,
        0.43058342,  0.42489678,  0.13460064, -0.38467026,  0.20833397],
      dtype=float32)

In [30]:
jnp.gradient(jax_arr)

DeviceArray([-1.6321278 , -0.6523524 ,  0.4904713 , -0.9367963 ,
             -0.6344316 ,  0.43058342,  0.42489678,  0.13460064,
             -0.38467026,  0.20833397], dtype=float32)

In [31]:
onp.gradient(np_arr, 0.025)

array([-65.28511  , -26.094095 ,  19.618853 , -37.47185  , -25.377264 ,
        17.223337 ,  16.99587  ,   5.3840256, -15.38681  ,   8.333359 ],
      dtype=float32)

In [32]:
jnp.gradient(jax_arr, 0.025)

DeviceArray([-65.28511  , -26.094095 ,  19.618853 , -37.47185  ,
             -25.377264 ,  17.223337 ,  16.99587  ,   5.3840256,
             -15.38681  ,   8.333359 ], dtype=float32)

In [33]:
onp.gradient(np_arr, 1.0)

array([-1.6321278 , -0.6523524 ,  0.4904713 , -0.9367963 , -0.6344316 ,
        0.43058342,  0.42489678,  0.13460064, -0.38467026,  0.20833397],
      dtype=float32)

In [34]:
onp.gradient(np_arr)

array([-1.6321278 , -0.6523524 ,  0.4904713 , -0.9367963 , -0.6344316 ,
        0.43058342,  0.42489678,  0.13460064, -0.38467026,  0.20833397],
      dtype=float32)

In [35]:
jnp.gradient(jax_arr)

DeviceArray([-1.6321278 , -0.6523524 ,  0.4904713 , -0.9367963 ,
             -0.6344316 ,  0.43058342,  0.42489678,  0.13460064,
             -0.38467026,  0.20833397], dtype=float32)

In [36]:
jnp.gradient(jax_arr, 1)

DeviceArray([-1.6321278 , -0.6523524 ,  0.4904713 , -0.9367963 ,
             -0.6344316 ,  0.43058342,  0.42489678,  0.13460064,
             -0.38467026,  0.20833397], dtype=float32)

In [38]:
jnp.gradient(jnp.ones(10,), 1)

DeviceArray([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)